import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        {children}
        <script  src="/assets/js/jquery.min.js" defer />
        <script  type="module"
          integrity="sha512-UyX8JsMsNRW1cYl8BoxpcamonpwU2y7mSTsN0Z52plp7oKo1u92Xqfpv6lOlTyH3yiMXK+gU1jw0DVCsPTfKew=="
          src="/assets/js/jquery.scrollify.min.js" defer />
        <script   src="/assets/js/scrool-view.js" defer/>
      </body>
    </html>
  )
}
